### ISSUE TITLE
У неавторизованных пользователей не удаляются товары из корзины

### ISSUE THREAD

**Issue by olegpro** [Convead/bitrix_convead#2]
CSaleBasket::Delete() возвращает false.

Подозреваю, что проблема в вашем обработчике cConveadTracker::updateCart на событие OnBeforeBasketDelete. Что это может быть и как пофиксить?

**Comment by rostber** [comment]
Здравствуйте.
При проблемах в работе curl этот метод действительно отправлял false.
Исправили в репозитории fdd601be9d7ea6bcfcbe7a43009e0b586f84aeb2
Чуть позже обновим в маркетплейсе. Спасибо.
